export const refs = {
  form: document.querySelector('.js-search-form'),
  list: document.querySelector('.js-gallery'),
  loader: document.querySelector('.js-loader'),
  paginationBlock: document.querySelector('#pagination'),
  header: document.querySelector('.header'),
  errText: document.querySelector('.header__text'),
  upBtn: document.querySelector('.up-link'),
  footer: document.querySelector('footer'),
  heart: document.querySelector('.heart-icon'),
  // teamModal: document.querySelector('[data-about-scream-modal]'),
  // openTeamModalBtn: document.querySelector('[data-about-scream-modal-open]'),
  // closeTeamModalBtn: document.querySelector('[data-about-scream-modal-close]'),
  // bestTeamBtn: document.querySelector('.button__modal-submit--team'),
  // closeCardModalBtn: document.querySelector('.btn-modal'),
  // cardBackdrop: document.querySelector('.js-backdrop'),
  // cardModalWindow: document.querySelector('.modal-window'),
  // cinemaInfo: document.querySelector('.cinema-info'),
  // closeAuthBtn: document.querySelector('.auth-backdrop-close'),
  // backDrop: document.querySelector('.backdrop-login'),
  // modalContent: document.querySelector('.login-modal__content'),
  // btnEmail: document.querySelector('.login-modal__email'),
  // btnGoogle: document.querySelector('.login-modal__google'),
  // btnLogin: document.querySelector('.js-login-btn'),
  // linkLibrary: document.querySelector('.js-header-library'),
};
